### ISSUE TITLE
Smarter trajectory handling

### ISSUE THREAD

**Issue by cadojo** [cadojo/GeneralAstrodynamics.jl#142]
# Trajectories could be better!

Right now, they're just `Vector`s of `Orbit` structures. This could be so much better for many reasons, including lots of memory allocation necessary to get a high degree of precision for trajectory calculations, and more. 

## Ideas for Improvement

* Allow for returning `ODESolution` structures from `propagate` with a `odesolution=Val{true}` switch, and manually add methods for applying astrodynamics calculations

I don't like that solution. Is there another?

## OrbitalTrajectories.jl

While watching Julia-related talks online, I found the [OrbitalTrajectories.jl](https://www.youtube.com/watch?v=FMVOUvWNlLE) talk. Turns out `OrbitalTrajectories` also uses `DifferentialEquations` for propagating orbits (no surprises there). What _is_ interesting is that the `ODESolution` object is returned directly from the propagation. That allows for interpolating by epoch, and access to `DifferentialEquations` [helper methods](https://diffeq.sciml.ai/stable/features/ensemble/#Summary-Statistics).

## Conclusion

* The `Trajectory` design by `OrbitalTrajectories` is far more robust. This should be the default, and a simple `Vector` of `Orbit` structures should be available via `vec=Val{true}`

**Comment by cadojo** [comment]
## Tasks

- [ ] Write tests to make sure this still works after the fact
- [ ] Re-do `CartesianState` and `Orbit` structures
- [ ] Re-do `Trajectory` structures
- [ ] Re-do `propagate` functions

**Comment by cadojo** [comment]
This was introduced in `v0.10`!
